### ISSUE TITLE
Error? when create new RemoteFileDownloader() with $preserve_filename = false

### ISSUE THREAD

**Issue by ISergeyV** [samundra/PHPFileDownloader#1]
in   ```  public function filewriter($buffer) ```
 line 123 ``` $filename = md5($fn . me_rand() . rand(5, 15)) . '.' . $ext; ```
error "me_rand()"
maybe "mt_rand()" !? work fine

**Comment by samundra** [comment]
Hi @ISergeyV,

Thanks for point out that. I don't know how I could have missed this. Looks like late refactor did it, will update it soon.

**Comment by samundra** [comment]
Fixed in #e61c145. Thank you.
